repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.286
    hooks:
    -   id: ruff
        args:
        - --fix
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.7.0
    hooks:
      - id: black
-   repo: https://github.com/python-poetry/poetry
    rev: 1.6.1
    hooks:
    -   id: poetry-export
        args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements/build.txt"]
        verbose: true
        always_run: true
    -   id: poetry-export
        args: ["--with=dev", "--without-hashes", "-f", "requirements.txt", "-o", "requirements/dev.txt"]
        verbose: true
        always_run: true
